Get the substatus of a failed assertion
perl-net-saml2/perl-Net-SAML2 pull request #157
Opened 2023-02-01 19:12 UTC by waterkip

This allows consumers to expose the reason of the failure.

Signed-off-by: Wesley Schwengle <waterkip@cpan.org>

2023-02-01 22:06 UTC, timlegge requested changes
Looks fine but needs some pod for the success and see other comment

2023-02-01 22:06 UTC, timlegge commented on lib/Net/SAML2/Protocol/Assertion.pm
> +sub success {
Also should have some pod here to describe success and point them to valid for full validation of the assertion

2023-02-02 10:46 UTC, waterkip commented on lib/Net/SAML2/Protocol/Assertion.pm
> +sub success {
We can add it to valid, but I do think the call itself should be seperate. The response is successful. Valid says a lot of things. A non-successful assertion can still be `valid()` in terms of correct audience, in response to and dates.

2023-02-02 11:05 UTC, timlegge approved these changes

2023-02-02 11:15 UTC, merged